#!/usr/bin/env groovy

//ENV Vars
def TOOLS_NAMESPACE = "4zq6uj-pdittaro-ocp201-tst-tools"
def DEV_NAMESPACE = "4zq6uj-pdittaro-ocp201-tst-dev"
def PROD_NAMESPACE = "4zq6uj-pdittaro-ocp201-tst-prod"

//Pipeline
node {
            stage ('Build Stage'){
                dir ('simple_pipeline') {
                    checkout scm
                    sh "ls -lha openshift/templates"
                    sh "oc get projects"
                }
            }
    }